### ISSUE TITLE
How do we know that we're using yolov4?

### ISSUE THREAD

**Issue by Kreijstal** [theAIGuysCode/YOLOv4-Cloud-Tutorial#2]
Instead of Yolov3, they all download the latest version of darknet, but all you do is change the cfg file you use?
Also are these people https://github.com/ultralytics/yolov5 developing yolo indepently, is it like a fork?
sorry, so many questions.

**Comment by theAIGuysCode** [comment]
Darknet is the framework that both YOLOv3 and YOLOv4 run on. It is the same for both of them. The cfg file is what lays out the deep learning architecture of the YOLO model. Thus having a different YOLOv4 cfg with different number of layers and type of layers is what distinguishes these two models the most. The ultralytics repo is an independent party that is trying to make advancements on YOLO, they have claimed to make a better YOLOv5 but it has been tested and found to pretty much be a copy of YOLOv3 and not better.
